inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  NewCops: enable
  # Exclude:
  #   - "bin/**/*"
  #   - "config/**/*"
  #   - "db/**/*"
  #   - "lib/**/*"
  #   - "spec/**/*.rb"
# Layout/HashAlignment:
#   Enabled: true
#   EnforcedHashRocketStyle: table
#   EnforcedColonStyle: table
#   EnforcedLastArgumentHashStyle: always_inspect

# Metrics/BlockLength:
#   Enabled: true
#   Max: 25
#   CountComments: false
#   Exclude:
#     - "app/api/**/*"

# Style/Documentation:
#   Enabled: false

# Metrics/MethodLength:
#   Enabled: false

# Layout/LineLength:
#   Enabled: false

# Layout/ExtraSpacing:
#   Enabled: true
#   AllowForAlignment: true
#   ForceEqualSignAlignment: false
