require: rubocop-rails

AllCops:
  Exclude:
    - "bin/**/*"
    - "config/**/*"
    - "db/**/*"
    - "lib/**/*"
    - "spec/**/*.rb"
  DisplayCopNames: true
  DisabledByDefault: true
  UseCache: true

Layout/HashAlignment:
  Enabled: true
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
  EnforcedLastArgumentHashStyle: always_inspect

Metrics/BlockLength:
  Enabled: true
  Max: 25
  CountComments: false
  Exclude:
    - "app/api/**/*"

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Enabled: false
